---
- name: Update package lists
  apt: update_cache=yes

- name: Install zsh
  apt: name=zsh state=present

- name: Install openssh
  apt: name=openssh-server state=present

- name: Install nfs-common
  apt: name=nfs-common state=present

- name: Install rsync
  apt: name=rsync state=present


#- name: Install several packages at once (pyhton dev)
#  apt: name {{ item }} state=present
#  with_items:
#    - python # silly, cause already installed
#    - python-dev
#    - python-virtualenv

- name: Create the 'vigo' user
  user: name=vigo shell=/bin/bash
  #user: name=vigo shell=/bin/bash groups=admins,developers append=yes

- name: Set zsh as default shell for vigo
  command: /usr/bin/chsh -s /usr/bin/zsh vigo

- name: Copy configuration for sshd
  template: src=sshdconfig.jinja2 dest=/etc/ssh/sshd_config
  notify: restart sshd
