---
galaxy_info:
  author: Emilien Mantel
  description: check_mk_agent on Debian based systems
  company:
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - vivid
    - wily
  - name: Debian
    versions:
    - jessie
  galaxy_tags:
  - monitoring
  - nagios
  - check_mk
  - check-mk
  - inetd
dependencies: []

