---

- name: ASSERT | Check variables
  assert:
    that: "mk_inetd_daemon in mk_inetd_daemon_managed"

- name: APT | Install related packages
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - "{{ mk_inetd_daemon }}"
    - check-mk-agent

- name: FILE | Unsure check config directory is created
  file: path={{ mk_conf_dir }} state=directory

- name: TEMPLATE | Deploy xinetd configuration
  template: >
    src=etc/xinetd.d/check_mk.j2
    dest=/etc/xinetd.d/check_mk
  when: mk_inetd_daemon == 'xinetd'
  notify: reload xinetd
